// assets.ts - CDN VERSION (auto-generated by Practa Manager)
// DO NOT EDIT - This file is regenerated on each publish

import { createAssetResolver } from "@stellarin/practa-runtime";

export type AssetKey = "sudoku-splash";

const assetUrls: Record<AssetKey, string> = {
  "sudoku-splash": "https://storage.googleapis.com/replit-objstore-b74bc498-5f8d-4fca-b9ba-531f07dd1cd0/practa/daily-sudoku/5ea9738f-b81c-448e-abbc-dfd32fda2bbc/sudoku_splash.png",
};

export const assets = createAssetResolver(assetUrls);
