// assets.ts - CDN VERSION (auto-generated by Practa Manager)
// DO NOT EDIT - This file is regenerated on each publish

import { createAssetResolver } from "@stellarin/practa-runtime";

export type AssetKey = "splash";

const assetUrls: Record<AssetKey, string> = {
  "splash": "https://storage.googleapis.com/replit-objstore-b74bc498-5f8d-4fca-b9ba-531f07dd1cd0/practa/chess-puzzles/afba5861-cc4d-4fc5-8596-6af927b5d17f/splash.png",
};

export const assets = createAssetResolver(assetUrls);
